#!/bin/bash
#A script for downloading various media links (namely imgur and sites supported by youtube-dl) from subreddits.
#Written by Sheg 
input="$1" 
time=all 	#Find top posts of all time, by default
max_par=6	#Maximum parallel video downloads
dir=~/lol/auto	#Directory to download subs to
vid_max=9999 	#Maximum video links to try

if test -z "$1" ; then
	input="random"
	echo "No subreddit specified."
	echo "Defaulting to $input."
fi

while getopts ":a:y:m:w:d:h:" opt; do
  case $opt in
    a)time=all;;
    y)time=year;;
    m)time=month;;
    w)time=week;;
    d)time=day;;
    h)time=hour;;
    \?)echo "Invalid option: -$OPTARG" >&2
       echo "Choose one letter from 'aymwdh'" >&2
       exit 1;;
  esac
input=$OPTARG
done

wget -q "reddit.com/r/$input/top/.rss?t=$time" -O ~/.rss
sub=$(tr \& \\n < ~/.rss  | grep "reddit.com/r/*.*/comments" -o | tail -n 1 | sed 's/.\{9\}$//; s/.\{13\}//')
mv ~/.rss ~/.rss_$sub 

if ls $dir | grep -q "$sub"; then
        echo "$sub(u)" >> ~/.new
	echo -e "\uf021  Updating $sub folder"
else
        echo "$sub" >> ~/.new
	echo -e "\uf019  Downloading new content: $sub"
	mkdir "$dir/$sub"
fi
 
tr \& \\n < ~/.rss_$sub | grep imgur | cut -c 1-4 --complement | sed -e 's/$/.jpg/' > ~/.imgur_$sub
echo -e "\uf019  Downloading $(cat ~/.imgur_$sub | wc -l) imgur links."
wget -nd -q --no-clobber -p -P $dir/$sub/ -i ~/.imgur_$sub

#Ugly but increasingly functional text parser
#Currently activated every time the script is run
sed "s/&lt;em&gt;/\*/g; s/&lt;\/em&gt;/\*/g; s/</\n/g; s/>/\n/g; s/&amp;quot;/\"/g; s/&lt;\/p&gt;/\n/g; s/&lt;p&gt;/\n/g; s/&amp;#39;/\'/g;" ~/.rss_$sub | egrep -v "\?xml|version=|/description|^?item|^/*$|https://|\;|\/guid|\/pubDate|PermaLink|\/link|\/channel|\/rss" | tr -s '\n' | sed 's/title/\n\n\nTITLE/g' > $dir/$sub/top_$time.txt

sed "s/</\n/g; s/\;/\n/g; s/\&/\n/g; s/>/\n/g; s/\"/\n/g" ~/.rss_$sub | egrep -i -f ~/git/redtop/source_list | grep http | uniq -u > ~/.pvideos_$sub
echo -e "\uf019  Downloading $(cat ~/.pvideos_$sub | wc -l) videos."
head -n $vid_max ~/.pvideos_$sub | xargs -P $max_par -I {} youtube-dl -w -o "$dir/$sub/%(title)s.%(ext)s" {}

find $dir/$sub 2>/dev/null -iname "*.png.jpg" -exec rename .png.jpg .png '{}' \;
find $dir/$sub 2>/dev/null -iname "*.jpg.jpg" -exec rename .jpg.jpg .jpg '{}' \;
find $dir/$sub 2>/dev/null -iname "*.gif.jpg" -exec rename .gif.jpg .gif '{}' \;
find $dir/$sub 2>/dev/null -iname "*.gifv.jpg" -exec rename .gifv.jpg .givf '{}' \;
rm ~/.*_$sub
echo ""
